name: dotent-restore

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build & Publish
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0' # SDK Version to use.
          source-url: https://nuget.pkg.github.com/namratajha/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m.%d')"
      - name: set env
        run: echo "version=${{ steps.date.outputs.date }}" >> $GITHUB_ENV
      - name: Restore Nuget packages
        run: dotnet restore -p:PackageVersion=${{ steps.date.outputs.date }}
      - name: Create the nuget package
        run: dotnet pack nuget-test.csproj --configuration Release --no-build --output bin/Release/Publish
      - name: Publish to GitHub
        run: dotnet nuget push bin/Release/Publish/**/*.nupkg --skip-duplicate
